const PDFDocument = require('pdfkit');
const fs = require('fs');

async function generateResumePdf(resumeData) {
  const {
    firstName = 'Candidate',
    lastName = 'User',
    email = 'candidate@email.com',
    phone = '(555) 123-4567',
    linkedin = 'linkedin.com/in/user',
    summary = 'No summary provided.',
    experience = [],
    education = [],
    skills = []
  } = resumeData;

  // 1. Construct the perfect ATS-Friendly Markdown
  const markdown = `
# ${firstName.toUpperCase()} ${lastName.toUpperCase()}

**Contact Information**
 ${email} | ${phone} | ${linkedin}

---

## Professional Summary
 ${summary}

---

## Professional Experience
 ${experience.map(exp => {
  let bullet = `- **${exp.role}** | **${exp.company}** | ${exp.duration}\n  - ${exp.points.map(p => `${p}`).join('\n  - ')}\n`;
  return bullet;
}).join('\n\n')}

---

## Education
 ${education.map(edu => `### ${edu.degree} | **${edu.institution}** | ${edu.year}\n  - GPA: ${edu.gpa || 'N/A'}\n`).join('\n\n')}

---

## Technical Skills
 ${skills.join(' | ')}

---

*Generated by Hirely AI*
`;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: `${firstName} ${lastName} - Resume`,
        Author: 'Hirely AI',
        Subject: 'ATS-Optimized Resume',
      }
    });

    const chunks = markdown.split('\n').filter(line => line.trim() !== '');
    
    chunks.forEach(line => {
      if (line.startsWith('# ')) {
        doc.moveDown();
        doc.fontSize(22).font('Helvetica-Bold').text(line.replace('# ', ''));
      } else if (line.startsWith('**') && line.endsWith('**')) {
        doc.fontSize(13).font('Helvetica-Bold').text(line.replace(/\*\*/g, ''));
      } else if (line.startsWith('---')) {
        doc.moveDown().moveDown();
      } else {
        doc.fontSize(11).font('Helvetica').text(line);
      }
      doc.moveDown(0.5);
    });

    // Pipe directly to response (Zero RAM usage, handles huge files safely)
    const pdfStream = doc.pipe(res => {
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${firstName}_${lastName}_Resume.pdf"`);
      res.end();
    });

    doc.end();
    pdfStream.on('finish', () => resolve(pdfStream));
    pdfStream.on('error', reject);
  });
}

module.exports = { generateResumePdf };