 const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');

/**
 * Convert an unknown value into a safe printable string.
 */
function safeText(value, fallback = '') {
  if (typeof value === 'string') {
    const trimmed = value.trim();
    return trimmed || fallback;
  }

  if (typeof value === 'number') {
    return String(value);
  }

  return fallback;
}

/**
 * Ensure the value is an array.
 */
function safeArray(value) {
  return Array.isArray(value) ? value : [];
}

/**
 * Create a safe filename for the Content-Disposition header.
 */
function createSafeFilename(firstName, lastName) {
  const fullName = `${firstName}_${lastName}`
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .replace(/_+/g, '_');

  return `${fullName || 'Hirely_Candidate'}_Resume.pdf`;
}

/**
 * Add an ATS-friendly section heading.
 */
function addSectionHeading(doc, title) {
  doc.moveDown(0.8);

  doc
    .font('Helvetica-Bold')
    .fontSize(12)
    .text(title.toUpperCase());

  const startX = doc.x;
  const lineY = doc.y + 2;
  const availableWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc
    .moveTo(startX, lineY)
    .lineTo(startX + availableWidth, lineY)
    .lineWidth(0.7)
    .stroke();

  doc.moveDown(0.6);
}

/**
 * Add a bullet point while keeping the layout simple for ATS systems.
 */
function addBulletPoint(doc, text) {
  const content = safeText(text);

  if (!content) {
    return;
  }

  doc
    .font('Helvetica')
    .fontSize(10.5)
    .text(`• ${content}`, {
      indent: 10,
      paragraphGap: 3,
      lineGap: 1,
    });
}

/**
 * Generate an ATS-friendly résumé PDF stream.
 *
 * The service does not know about Express req/res.
 * It only creates the PDF and returns its stream and filename.
 */
function generateResumePdf(resumeData = {}) {
  if (
    !resumeData ||
    typeof resumeData !== 'object' ||
    Array.isArray(resumeData)
  ) {
    throw new TypeError('Resume data must be an object.');
  }

  const firstName = safeText(resumeData.firstName, 'Candidate');
  const lastName = safeText(resumeData.lastName, 'User');
  const email = safeText(resumeData.email);
  const phone = safeText(resumeData.phone);
  const linkedin = safeText(resumeData.linkedin);
  const location = safeText(resumeData.location);
  const portfolio = safeText(resumeData.portfolio);
  const summary = safeText(resumeData.summary);

  const experience = safeArray(resumeData.experience);
  const education = safeArray(resumeData.education);
  const skills = safeArray(resumeData.skills);
  const projects = safeArray(resumeData.projects);
  const certifications = safeArray(resumeData.certifications);

  const outputStream = new PassThrough();

  const doc = new PDFDocument({
    size: 'LETTER',
    margins: {
      top: 45,
      bottom: 45,
      left: 50,
      right: 50,
    },
    bufferPages: true,
    info: {
      Title: `${firstName} ${lastName} - Resume`,
      Author: `${firstName} ${lastName}`,
      Subject: 'ATS-Optimized Resume generated by Hirely AI',
      Creator: 'Hirely AI',
    },
  });

  doc.pipe(outputStream);

  // Candidate name
  doc
    .font('Helvetica-Bold')
    .fontSize(21)
    .text(`${firstName} ${lastName}`.toUpperCase(), {
      align: 'center',
    });

  // Contact details
  const contactDetails = [
    email,
    phone,
    location,
    linkedin,
    portfolio,
  ].filter(Boolean);

  if (contactDetails.length > 0) {
    doc.moveDown(0.35);

    doc
      .font('Helvetica')
      .fontSize(9.5)
      .text(contactDetails.join(' | '), {
        align: 'center',
        link: undefined,
      });
  }

  // Professional summary
  if (summary) {
    addSectionHeading(doc, 'Professional Summary');

    doc
      .font('Helvetica')
      .fontSize(10.5)
      .text(summary, {
        align: 'left',
        lineGap: 1.5,
      });
  }

  // Experience
  if (experience.length > 0) {
    addSectionHeading(doc, 'Professional Experience');

    experience.forEach((item, index) => {
      const role = safeText(item?.role, 'Position');
      const company = safeText(item?.company);
      const locationText = safeText(item?.location);
      const duration = safeText(item?.duration);

      const headingParts = [role, company].filter(Boolean);
      const detailParts = [locationText, duration].filter(Boolean);

      doc
        .font('Helvetica-Bold')
        .fontSize(10.5)
        .text(headingParts.join(' | '), {
          continued: false,
        });

      if (detailParts.length > 0) {
        doc
          .font('Helvetica-Oblique')
          .fontSize(9.5)
          .text(detailParts.join(' | '));
      }

      const points = Array.isArray(item?.points)
        ? item.points
        : item?.points
          ? [item.points]
          : [];

      points.forEach((point) => addBulletPoint(doc, point));

      if (index < experience.length - 1) {
        doc.moveDown(0.45);
      }
    });
  }

  // Projects
  if (projects.length > 0) {
    addSectionHeading(doc, 'Projects');

    projects.forEach((project, index) => {
      const name = safeText(project?.name, 'Project');
      const technologies = Array.isArray(project?.technologies)
        ? project.technologies.filter(Boolean).join(', ')
        : safeText(project?.technologies);

      doc.font('Helvetica-Bold').fontSize(10.5).text(name);

      if (technologies) {
        doc
          .font('Helvetica-Oblique')
          .fontSize(9.5)
          .text(`Technologies: ${technologies}`);
      }

      const points = Array.isArray(project?.points)
        ? project.points
        : project?.description
          ? [project.description]
          : [];

      points.forEach((point) => addBulletPoint(doc, point));

      if (index < projects.length - 1) {
        doc.moveDown(0.45);
      }
    });
  }

  // Education
  if (education.length > 0) {
    addSectionHeading(doc, 'Education');

    education.forEach((item, index) => {
      const degree = safeText(item?.degree, 'Qualification');
      const institution = safeText(item?.institution);
      const locationText = safeText(item?.location);
      const year = safeText(item?.year);
      const gpa = safeText(item?.gpa);

      doc
        .font('Helvetica-Bold')
        .fontSize(10.5)
        .text([degree, institution].filter(Boolean).join(' | '));

      const details = [locationText, year].filter(Boolean);

      if (details.length > 0) {
        doc
          .font('Helvetica-Oblique')
          .fontSize(9.5)
          .text(details.join(' | '));
      }

      if (gpa) {
        doc
          .font('Helvetica')
          .fontSize(9.5)
          .text(`GPA: ${gpa}`);
      }

      if (index < education.length - 1) {
        doc.moveDown(0.4);
      }
    });
  }

  // Skills
  if (skills.length > 0) {
    addSectionHeading(doc, 'Skills');

    const formattedSkills = skills
      .map((skill) => {
        if (typeof skill === 'string') {
          return skill.trim();
        }

        return safeText(skill?.name);
      })
      .filter(Boolean);

    doc
      .font('Helvetica')
      .fontSize(10.5)
      .text(formattedSkills.join(' | '), {
        lineGap: 2,
      });
  }

  // Certifications
  if (certifications.length > 0) {
    addSectionHeading(doc, 'Certifications');

    certifications.forEach((certification) => {
      if (typeof certification === 'string') {
        addBulletPoint(doc, certification);
        return;
      }

      const name = safeText(certification?.name);
      const issuer = safeText(certification?.issuer);
      const year = safeText(certification?.year);

      addBulletPoint(
        doc,
        [name, issuer, year].filter(Boolean).join(' | ')
      );
    });
  }

  doc.end();

  return {
    stream: outputStream,
    filename: createSafeFilename(firstName, lastName),
  };
}

module.exports = {
  generateResumePdf,
};